runtime: python39
instance_class: F1

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  # Set environment variables required by API
  VARIABLE_NAME: "variable_value"
  MODEL_PATH: "/Users/kheylaramadhanihakim/Downloads/model.h5"
  IMAGE_SIZE: "256"
  CONFIDENCE_THRESHOLD: "0.5"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /.*
  script: auto
